target_phrase_sections = [
    ("Racism/Hate Speech", [
        "moslem", "mulatto", "sand nigger", "sandnig", "nigger", "mogger", "negroid", "jew", "kike", "zogbot",
        "chink", "paki", "mudslime", "mudshit", "femoid", "foid", "mongrel",
        "towel 	head", "towelhead", "moslems", "mulattos", "muzzies", "sand niggers", "sandnigs", "shit skin",
        "shitskin", "niggers", "moggers", "negroids", "jews", "kikes", "zogbots",
        "chinks", "pakis", "mudslimes", "mudshits", "femoids", "mongrels", "towel heads", "towelheads", "spics",
        "gooks", "rapefugees", "shitskins", "fag", "fags", "faggot", "faggots",
        "groomer", "groomers", "tranny", "trannys", "jewish", "(((", "Gibsmedat", "Goy", "soyboy", "gibs",
        "soyboys",
    ]),
    ("White Identity Motivated Extremism", [
        # List of target phrases for section 2
        "white genocide", "cultural marxism", "cultural marxists", "the great replacement", "white race",
        "demographic replacement", "demographic decline", "anti-Zionist",
        "#WhiteLivesMatter", "white lives matter", "white pride", "ethnostate", "hitler", "Tarrant", "brevik",
        "white nationalist", "ethno-nationalist", "kebab removalist", "remove kebab",
        "remove kebabs", "Aryan", "1488", "14-88", "14/88", "1788", "88/HH", "blood and soil", "RACE WAR NOW",
        "RaHoWa", "Racial Holy War", "FGRN", "GTKRWN", "IOTBW", "jewish question",
        "accelerate", "accelerationist", "sieg heil", "siege pill", "siege pilled", "white power", "goyim",
        "zyklon B", "14 words", "race traitors", "race traitor", "day of the rope",
        "waffen", "iron pill", "iron pilled", "ZOG", "Z.O.G.", "terrorgram", "national socialist",
        "national socialism", "⚡", "//", "Khazarian", "Ashkenazis",
        "tradwife", "tradthot", "cultural jihad", "pro western values", "pro-western values", "western culture",
        "kek", "deus vault", "did nothing wrong", "its okay to be white",
        "it's okay to be white", "it's ok to be white", "white is right", "pro-white activism", "coal burner",
        "race traitor", "race traitors", "6MWNE", "Holocauster", "Holohoax",
        "Clown World", "🤡🌎", "Accelerationist", "James Mason", "Accelerationism",
    ]),
    ("Faith Motivated Extremism", [
        # List of target phrases for section 2
        "جهاد", "جهاد", "مرتد", "المرتدين", "الطغاة", "التحالف الصليبي", "جنود الخلافة", "أسود الدولة الإسلامية",
        "في ظل الخلافة", "تقبل الله الله", "المنهجية المؤيدة للفيتيك", "المنهج النبوي", "المتبقية والتوسع",
        "موسوعة الجهاد", "دليل المجاهد", "رفيدة", "الدولة الإسلامية", "الخلافة الإسلاميةروافيض", "استيشادي",
        "باقية من تاتاداد", "التواغيت", "الشريعة",
        "Jihad", "holy war", "apostate", "the apostates", "tyrants", "the crusader coalition",
        "soldiers of the caliphate", "lions of the Islamic State", "in the shadow of the caliphate",
        "may God accept him", "the prophetic methodology", "the prophetic methodology", "Remaining and Expanding",
        "The encyclopedia of Jihad", "The Mujahad’s Handbook", "Rafidha", "Rawafidh",
        "Istishaadi", "Baqiya wa tatamaddad", "al-Tawaghit", "shariyah", "A’maq Agency", "Al-hayat", "al-Emarah",
        "Dabiq",
    ]),
    ("Conspiratorial Ideation", [
        "great awakening", "globalist", "globalists", "new world order", "WWG1WGA", "the storm", "chemtrails",
        "freemasons", "freemason", "illuminati", "deep state", "the storm",
        "adrenochrome", "cabal", "rothschilds", "nuremberg", "nuremburg", "crimes against humanity", "great reset",
        "agenda 2030", "agenda 21", "world economic forum", "false flag",
        "Microchipped", "microchips", "pizzagate", "sheeple", "geotus",
    ]),
    ("Sovereign Citizen", [
        "sovreign citizen", "sovereign citizen", "free man", "free woman", "flesh and blood", "common law",
        "admiralty law", "non-resident alien", "14th amendment", "legal fiction",
        "notice of understanding and intent", "affidavit of truth", "Birth Certificate Bond",
        "Non-Domiciled Resident", "Natural Law", "Freeman Passport", "Constitutional Sheriff",
        "Nontaxpayer", "Informed Consent", "Commercial Redemption", "Freemen Standby Act", "strawman",
        "man on the land", "non-resident alien", "in admiralty",
        "living soul", "letters of marque", "Settlor", "Quantam Grammar", "Quantum Grammar", "Strawman",
        "Magna Carta", "Maritime Law", "Policy Officer", "Postmaster",
        "Artifical Construct", "Artificial Construct", "Lawful Dissent", "In the Private", "living man",
        "living woman", "Maxim of Law", "Uniform Commercial Code", "Corpus Juris", "Sui Juris",
    ]),
    ("Involuntary Celibate", [
        "foid", "femoid", "dog pill", "dog pilled", "red pill", "red pilled", "going ER", "truecel", "incel",
        "chad", "fakecel", "black pilled", "blackpilled", "ragefuel", "rape fuel",
        "ropefuel", "Supreme Gentleman", "Elliot Rodger", "braincels", "genetically inferior", "roasties", "SMV",
        "Sexual Market Value", "have a little fun bEfoRe you go", "red-pilled",
        "cucks", "Manosphere", "incels", "incel", "Mens Rights Activists", "MGTOW", "Men going their own way",
        "alpha male", "beta male", "omega male", "gamma male",
    ]),
    ("Dehumanizing Rhetoric", [
        "parasite", "scum", "demon", "demonic", "soulless", "vermin", "parasites", "mongrel", "mongrels", "leeches",
        "leech", "maggot", "maggots", "parasites", "sub-human",
    ]),

    ("Brazilian CVV scam", [
        "carder", "cc", "info cc", "cc/info", "checker", "gg", "devs", "lives", "live", "bin", "bin baixa", "bin mediana",
         "bin alta", "die", "cc fuzil", "consultavel", "consultável", "full", "cc full", "cvv", "baker", "info baker", "mix",
         "gold", "golds", "unitaria", "classic", "standard", "aprovação", "aprovacao", "editável", "editavel", "pax", "material",
         "esquemas", "referencias", "referências", "drop", "drops", "lara", "extraviado", "db", "painel", "puxada", "tela fake",
         "fakes", "banner", "banners", "lotter",
    ]),
]
